version: "3"
services:
  iptv-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # If your are using local m3u file instead of m3u remote file
      # put your m3u file in this folder
      - ./iptv:/root/iptv
    container_name: "iptv-proxy"
    restart: on-failure
    ports:
       # have to be the same as ENV variable PORT
      - 8080:8080
    environment:
      # if you are using m3u remote file
      # M3U_URL: https://example.com/iptvfile.m3u
      M3U_URL: http://line.kemotv.cc/get.php?username=8gY5ypD3SC&password=536544781354&type=m3u_plus&output=m3u8
      # Port to expose the IPTVs endpoints
      PORT: 8080
      # Hostname or IP to expose the IPTVs endpoints (for machine not for docker)
      HOSTNAME: testing.info
      GIN_MODE: release
      ## Xtream-code proxy configuration
      XTREAM_USER: 8gY5ypD3SC
      XTREAM_PASSWORD: 536544781354
      XTREAM_BASE_URL: "http://line.kemotv.cc"
      ##### UNSAFE AUTH TODO ADD REAL AUTH
      #will be used for m3u and xtream auth poxy
      USER: test
      PASSWORD: testpassword

